use car_info;
 SELECT model,count(description) as count from car where description is not null ;
 SELECT AVG(model_year) as count from car;
 select min(price) as max,max(price),count(price) as count from car;
 select count(price) as count,sum(price) as sum from car where manufacturer = 'bmw' or manufacturer = 'audi';
 select UCASE(manufacturer),model, round(price,1) from car where manufacturer = 'fiat';
 select manufacturer,model, mid(description,1,7 ) from car where description is not null order by model;
 select model, now() from car limit 5;
 select manufacturer,model from car where car.model like '__';
 select manufacturer,model from car where manufacturer not in('Audi','skoda','bmw');
select * from car;
 UPDATE car SET color = 'BLACK' WHERE manufacturer = 'Fiat';
 update car set model_year = 2005 where manufacturer = 'lambo';
 update car set  price = 5500 where id =4;
 ALTER TABLE car drop column  description;
 ALTER TABLE car ADD description varchar(20);
 ALTER TABLE  car modify column description text;
 ALTER TABLE car rename column description to descr;
DELETE from vendors;